export const imageSelector = {
  Ash: "assets/ash.jpg",
  Clouds: "assets/brokenClouds.jpg",
  Clear: "assets/clearSky.jpg",
  Dust: "assets/dust.jpg",
  Fog: "assets/fog.jpg",
  Haze: "assets/haze.jpg",
  Mist: "assets/mist.jpg",
  Drizzle: "assets/drizzle.jpg",
  Rain: "assets/rain.jpg",
  Sand: "assets/sand.jpg",
  Smoke: "assets/smoke.jpg",
  Snow: "assets/snow.jpg",
  Squall: "assets/squall.jpg",
  Thunderstorm: "assets/thunderStorm.jpg",
  Tornado: "assets/tornado.jpg",
};
